// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: protofile.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PingPongService_HandleMessage_FullMethodName = "/main.PingPongService/HandleMessage"
)

// PingPongServiceClient is the client API for PingPongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingPongServiceClient interface {
	HandleMessage(ctx context.Context, opts ...grpc.CallOption) (PingPongService_HandleMessageClient, error)
}

type pingPongServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingPongServiceClient(cc grpc.ClientConnInterface) PingPongServiceClient {
	return &pingPongServiceClient{cc}
}

func (c *pingPongServiceClient) HandleMessage(ctx context.Context, opts ...grpc.CallOption) (PingPongService_HandleMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &PingPongService_ServiceDesc.Streams[0], PingPongService_HandleMessage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongServiceHandleMessageClient{stream}
	return x, nil
}

type PingPongService_HandleMessageClient interface {
	Send(*PingMessage) error
	Recv() (*PongMessage, error)
	grpc.ClientStream
}

type pingPongServiceHandleMessageClient struct {
	grpc.ClientStream
}

func (x *pingPongServiceHandleMessageClient) Send(m *PingMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingPongServiceHandleMessageClient) Recv() (*PongMessage, error) {
	m := new(PongMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingPongServiceServer is the server API for PingPongService service.
// All implementations must embed UnimplementedPingPongServiceServer
// for forward compatibility
type PingPongServiceServer interface {
	HandleMessage(PingPongService_HandleMessageServer) error
	mustEmbedUnimplementedPingPongServiceServer()
}

// UnimplementedPingPongServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPingPongServiceServer struct {
}

func (UnimplementedPingPongServiceServer) HandleMessage(PingPongService_HandleMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method HandleMessage not implemented")
}
func (UnimplementedPingPongServiceServer) mustEmbedUnimplementedPingPongServiceServer() {}

// UnsafePingPongServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingPongServiceServer will
// result in compilation errors.
type UnsafePingPongServiceServer interface {
	mustEmbedUnimplementedPingPongServiceServer()
}

func RegisterPingPongServiceServer(s grpc.ServiceRegistrar, srv PingPongServiceServer) {
	s.RegisterService(&PingPongService_ServiceDesc, srv)
}

func _PingPongService_HandleMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingPongServiceServer).HandleMessage(&pingPongServiceHandleMessageServer{stream})
}

type PingPongService_HandleMessageServer interface {
	Send(*PongMessage) error
	Recv() (*PingMessage, error)
	grpc.ServerStream
}

type pingPongServiceHandleMessageServer struct {
	grpc.ServerStream
}

func (x *pingPongServiceHandleMessageServer) Send(m *PongMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingPongServiceHandleMessageServer) Recv() (*PingMessage, error) {
	m := new(PingMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingPongService_ServiceDesc is the grpc.ServiceDesc for PingPongService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingPongService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.PingPongService",
	HandlerType: (*PingPongServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleMessage",
			Handler:       _PingPongService_HandleMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protofile.proto",
}
